# Generated by Django 4.2.15 on 2024-08-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='管线名称')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='桩号')),
                ('orientation', models.CharField(blank=True, max_length=255, null=True, verbose_name='平面转角')),
                ('length_km', models.FloatField(blank=True, null=True, verbose_name='里程 (单位: Km)')),
                ('depth_m', models.FloatField(blank=True, null=True, verbose_name='管道埋深 (单位: m)')),
                ('distance_position_des', models.TextField(blank=True, null=True, verbose_name='离管道位置描述')),
                ('wall_thickness_mm', models.FloatField(blank=True, null=True, verbose_name='壁厚 (单位: mm)')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='材质')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('qr_code_url', models.URLField(blank=True, null=True, verbose_name='二维码地址')),
            ],
        ),
    ]
