# Generated by Django 4.2.15 on 2024-08-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipline', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pipeline',
            new_name='Pipelines',
        ),
    ]
